name: Build Angular App 

on:
  push:
    branches: [main]
  workflow_dispatch:
 
jobs:
  build-angular:
    runs-on: ubuntu-latest
    concurrency:
      group: ci-${{ github.workflow }}
      cancel-in-progress: true
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python and Node JS
        uses: Dnzldotexe/github-actions-practice/InstallPythonNodeJsAction@main
        
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./dist

  deploy-angular:
    runs-on: ubuntu-latest
    needs: build-angular
    concurrency:
      group: cd-${{ github.workflow }}
      cancel-in-progress: true
    
    steps:
      - name: Sleep
        run: sleep 60
