name: Deploy Angular App

on:
  workflow_dispatch:

jobs:
  deploy-angular:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v4
        with:
          name: build-artifact
          path: ./artifact
          workflow: build-angular.yml
          github-token: ${{ github.token }}
          repo: ${{ github.repository }}
          run_number: 20
      
      - name: Display downlaoded artifact structure
        run: ls -R ./artifact
