name: Build and Deploy Angular App 

on:
  workflow_call:
    inputs:
      pythonVersion:
        required: true
        type: string
      nodejsVersion:
        required: true
        type: string

jobs:
  build-angular:
    runs-on: ubuntu-latest
    concurrency:
      group: ci-${{ github.workflow }}
      cancel-in-progress: true
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Build Environment
        id: setup-build-env
        uses: ./SetupBuildEnvironmentAction
        with:
          pythonVersion: ${{ inputs.pythonVersion }}
          nodejsVersion: ${{ inputs.nodejsVersion }}

      - name: Outputs from action
        run: |
          echo "Repository Owner = ${{ steps.setup-build-env.outputs.repoOwner }}"
          echo "Default Branch = ${{ steps.setup-build-env.outputs.defaultBranch }}"
          echo "CI CD Key = ${{ steps.setup-build-env.outputs.cicdKey }}"
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./dist

  deploy-angular:
    runs-on: ubuntu-latest
    needs: build-angular
    concurrency:
      group: cd-${{ github.workflow }}
      cancel-in-progress: true
    
    steps:
      - name: Sleep
        run: sleep 60
